credentials:
  usernames:
    felicitaklix:
      email: felicitas@bullmetrix.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Felicitas Klix
      password: FelicitasBull123 # Will be hashed automatically
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Rebecca Briggs
      password: def # Will be hashed automatically
cookie:
  expiry_days: 30
  key: "abcdefghijklmnopqrtsuvwxyz" # Must be string
  name: "scriptrepositorycookie"
pre-authorized:
  emails:
  - felicitas@bullmetrix.com